# Generated by Django 3.1.5 on 2021-01-27 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gamelist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название игры')),
                ('link_game', models.CharField(max_length=250, verbose_name='URL игры')),
                ('link_img', models.CharField(max_length=250, verbose_name='URL изображения')),
                ('alt_text', models.CharField(max_length=250, verbose_name='Альтернативный текст')),
                ('discript', models.TextField(verbose_name='Описание игры')),
                ('janr', models.CharField(max_length=250, verbose_name='Жанр игры')),
                ('type', models.CharField(max_length=250, verbose_name='Тип игры')),
                ('osobenosti', models.TextField(verbose_name='Особенности игры')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
            },
        ),
    ]
